version: '2.1'

services:
        atomizer-ui:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: atomizer-test-ui
                ports:
                        - 3000:3000
                depends_on:
                        - "rabbit-mq"
                        - "atomizer-node1"
                        - "atomizer-node2"
                        - "atomizer-node3"
                environment:
                        - RABBIT_NAME=atomrabbit
                        - QUEUE=atomizer
                        - APPID=0f7827a0-0baa-11ea-a738-a707993eaee1
                          #command: ./wait-for.sh --timeout=30 atomrabbit:5672 -- node /app/server.js
        rabbit-mq:
                image: 'rabbitmq:3-management'
                container_name: atomrabbit
                hostname: atomrabbit
                ports:
                        - 8080:15672
                        - 5672:5672
        atomizer-node1:
                image: 'devnw/atomizer-test:latest'
                depends_on:
                        - "rabbit-mq"
                environment:
                        - CONNECTIONSTRING=amqp://guest:guest@atomrabbit:5672/
                        - QUEUE=atomizer
        atomizer-node2:
                image: 'devnw/atomizer-test:latest'
                depends_on:
                        - "rabbit-mq"
                environment:
                        - CONNECTIONSTRING=amqp://guest:guest@atomrabbit:5672/
                        - QUEUE=atomizer
        atomizer-node3:
                image: 'devnw/atomizer-test:latest'
                depends_on:
                        - "rabbit-mq"
                environment:
                        - CONNECTIONSTRING=amqp://guest:guest@atomrabbit:5672/
                        - QUEUE=atomizer
