name: CI

# this is triggered on push to the repository
on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build:prod --if-present
